[GLOBAL]
pants_version = '2.14.0+gitfae1f69f'
backend_packages = [
  "pants.backend.python",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/", "/tests"]

[python]
interpreter_constraints = ["==3.9.*"]

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]